"modifier_warrior_counter_stance_strike" 
{ 
    "critrate"
    {
    	"1"	"wizard_blizzard"
    	"2"	"modifier_bard_symphony_lyre"
    	"3"	"modifier_bard_discord_lyre"
    	"4"	"modifier_bard_finesse"
        "5" "modifier_ranger_heighten_senses"
    	"6"	"modifier_item_basic_spear"
    }
     "critdamage"
    {
    	"1"	"wizard_blizzard"
    }
    "critstrike"
    {
    	"1"	"modifier_item_triple_head_crit"
    }
}