"types"
{
	"fire"
	{
		"fire"		"0.5"
		"water"		"0.5"
		"ice"		"2"
		"earth"		"0.5"
		"storm"		"1"
		"poison"	"1"
		"dark"		"1"
		"holy"		"0.5"

		"celestial"	"1"
		"demon"		"1"
		"dragon"	"0.5"
		"insect"	"2"
		"fairy"		"1"
		"beast"		"1"
		"ghost"		"1"
		
	}		

	"water"
	{
		"fire"		"2"
		"water"		"1"
		"ice"		"1"
		"earth"		"2"
		"storm"		"1"
		"poison"	"1"
		"dark"		"1"
		"holy"		"0.5"

		"celestial"	"1"
		"demon"		"1"
		"dragon"	"0.5"
		"insect"	"1"
		"fairy"		"1"
		"beast"		"1"
		"ghost"		"1"
		
	}		

	"ice"
	{
		"fire"		"0.5"
		"water"		"1"
		"ice"		"0.5"
		"earth"		"1"
		"storm"		"1"
		"poison"	"1"
		"dark"		"1"
		"holy"		"0.5"

		"celestial"	"1"
		"demon"		"1"
		"dragon"	"0.5"
		"insect"	"2"
		"fairy"		"1"
		"beast"		"1.5"
		"ghost"		"0.5"
		
	}		

	"earth"
	{
		"fire"		"2"
		"water"		"0.5"
		"ice"		"1"
		"earth"		"0.5"
		"storm"		"1.75"
		"poison"	"2"
		"dark"		"1"
		"holy"		"0.5"

		"celestial"	"1"
		"demon"		"1"
		"dragon"	"1"
		"insect"	"1"
		"fairy"		"1"
		"beast"		"0.5"
		"ghost"		"1"
		
	}		

	"storm"
	{
		"fire"		"1"
		"water"		"0.5"
		"ice"		"2"
		"earth"		"0.5"
		"storm"		"0.5"
		"poison"	"1"
		"dark"		"1"
		"holy"		"0.5"

		"celestial"	"1"
		"demon"		"1"
		"dragon"	"0.5"
		"insect"	"2"
		"fairy"		"1"
		"beast"		"0.5"
		"ghost"		"2"
		
	}		

	"poison"
	{
		"fire"		"1"
		"water"		"2"
		"ice"		"1"
		"earth"		"0.5"
		"storm"		"1"
		"poison"	"0"
		"dark"		"1"
		"holy"		"0.5"

		"celestial"	"1"
		"demon"		"1"
		"dragon"	"0.5"
		"insect"	"2"
		"fairy"		"2"
		"beast"		"1.75"
		"ghost"		"0.5"
		
	}		

	"dark"
	{
		"fire"		"2"
		"water"		"2"
		"ice"		"2"
		"earth"		"2"
		"storm"		"2"
		"poison"	"1"
		"dark"		"0.5"
		"holy"		"0.5"

		"celestial"	"0.5"
		"demon"		"1"
		"dragon"	"1"
		"insect"	"1"
		"fairy"		"0.5"
		"beast"		"1"
		"ghost"		"1"
		
	}		

	"holy"
	{
		"fire"		"1"
		"water"		"1"
		"ice"		"1"
		"earth"		"1"
		"storm"		"1"
		"poison"	"1"
		"dark"		"2"
		"holy"		"0.5"

		"celestial"	"1"
		"demon"		"2"
		"dragon"	"1"
		"insect"	"1"
		"fairy"		"1"
		"beast"		"1"
		"ghost"		"2"
		
	}		

	"pierce"
	{
		"fire"		"1"
		"water"		"1"
		"ice"		"2"
		"earth"		"0.5"
		"storm"		"1"
		"poison"	"1"
		"dark"		"1"
		"holy"		"1"

		"celestial"	"1"
		"demon"		"1"
		"dragon"	"0.5"
		"insect"	"2"
		"fairy"		"1"
		"beast"		"1"
		"ghost"		"1"
		
	}		

	"slash"
	{
		"fire"		"1"
		"water"		"1"
		"ice"		"2"
		"earth"		"0.5"
		"storm"		"1"
		"poison"	"1"
		"dark"		"1"
		"holy"		"1"

		"celestial"	"1"
		"demon"		"1"
		"dragon"	"0.5"
		"insect"	"2"
		"fairy"		"1"
		"beast"		"1"
		"ghost"		"1"
		
	}			

	"strike"
	{
		"fire"		"1"
		"water"		"1"
		"ice"		"2"
		"earth"		"0.5"
		"storm"		"1"
		"poison"	"1"
		"dark"		"1"
		"holy"		"1"

		"celestial"	"1"
		"demon"		"1"
		"dragon"	"0.5"
		"insect"	"2"
		"fairy"		"1"
		"beast"		"1"
		"ghost"		"1"
		
	}		

	"arrow"
	{
		"fire"		"1"
		"water"		"1"
		"ice"		"2"
		"earth"		"0.5"
		"storm"		"1"
		"poison"	"1"
		"dark"		"1"
		"holy"		"1"

		"celestial"	"1"
		"demon"		"1"
		"dragon"	"0.5"
		"insect"	"2"
		"fairy"		"1"
		"beast"		"1"
		"ghost"		"1"
		
	}		

	"missile"
	{
		"fire"		"1"
		"water"		"1"
		"ice"		"2"
		"earth"		"0.5"
		"storm"		"1"
		"poison"	"1"
		"dark"		"1"
		"holy"		"1"

		"celestial"	"1"
		"demon"		"1"
		"dragon"	"0.5"
		"insect"	"2"
		"fairy"		"1"
		"beast"		"1"
		"ghost"		"0.5"
		
	}		

	"chaos"
	{
		"fire"		"1"
		"water"		"1"
		"ice"		"1"
		"earth"		"1"
		"storm"		"1"
		"poison"	"1"
		"dark"		"1"
		"holy"		"1"

		"celestial"	"2"
		"demon"		"2"
		"dragon"	"1"
		"insect"	"1"
		"fairy"		"1"
		"beast"		"1"
		"ghost"		"1"
		
	}	

}